COW-dev/ddingdong-be

build.gradle
src/main/java/ddingdong/ddingdongBE/DdingdongBeApplication.java
src/main/java/ddingdong/ddingdongBE/auth/PrincipalDetails.java
src/main/java/ddingdong/ddingdongBE/auth/controller/AuthAPiController.java
src/main/java/ddingdong/ddingdongBE/auth/controller/dto/request/SignInRequest.java
src/main/java/ddingdong/ddingdongBE/auth/controller/dto/response/SignInResponse.java
src/main/java/ddingdong/ddingdongBE/auth/service/AuthService.java
src/main/java/ddingdong/ddingdongBE/auth/service/JwtAuthService.java
src/main/java/ddingdong/ddingdongBE/common/BaseEntity.java
src/main/java/ddingdong/ddingdongBE/common/config/JpaAuditingConfig.java
src/main/java/ddingdong/ddingdongBE/common/config/JwtConfig.java
src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
src/main/java/ddingdong/ddingdongBE/common/filter/JwtAuthenticationFilter.java
src/main/java/ddingdong/ddingdongBE/domain/user/entity/Password.java
src/main/java/ddingdong/ddingdongBE/domain/user/entity/User.java
src/main/java/ddingdong/ddingdongBE/domain/user/repository/UserRepository.java
src/main/resources/application.yaml
src/test/java/ddingdong/ddingdongBE/domain/user/repository/UserRepositoryTest.java

[Feat] 로그인 기능 구현

---

src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
src/main/java/ddingdong/ddingdongBE/domain/club/controller/AdminApiController.java
src/main/java/ddingdong/ddingdongBE/domain/club/controller/AdminClubApiController.java
src/main/java/ddingdong/ddingdongBE/domain/club/controller/CentralClubApiController.java
src/main/java/ddingdong/ddingdongBE/domain/club/controller/UserClubApiController.java
src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/request/RegisterClubRequest.java
src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/request/UpdateClubRequest.java
src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/AdminClubResponse.java
src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/ClubResponse.java
src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/DetailClubResponse.java
src/main/java/ddingdong/ddingdongBE/domain/club/entity/Club.java
src/main/java/ddingdong/ddingdongBE/domain/club/entity/Score.java
src/main/java/ddingdong/ddingdongBE/domain/club/repository/ClubRepository.java
src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubService.java
src/main/resources/application.yaml
src/main/resources/data.sql

Admin - 동아리 등록, 동아리 목록 조회, 동아리 삭제, 동아리 점수 수정
Central - 내 동아리 정보 조회, 동아리 정보 수정
User - 동아리 목록 조회, 동아리 상세 조회

[Feat] 동아리 기능 구현

---

src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
src/main/java/ddingdong/ddingdongBE/domain/notice/controller/AdminNoticeApiController.java
src/main/java/ddingdong/ddingdongBE/domain/notice/controller/NoticeApiController.java
src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/request/RegisterNoticeRequest.java
src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/request/UpdateNoticeRequest.java
src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/response/DetailNoticeResponse.java
src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/response/NoticeResponse.java
src/main/java/ddingdong/ddingdongBE/domain/notice/entity/Notice.java
src/main/java/ddingdong/ddingdongBE/domain/notice/repository/NoticeRepository.java
src/main/java/ddingdong/ddingdongBE/domain/notice/service/NoticeService.java

Admin - 공지사항 등록, 공지사항 수정, 공지사항 삭제
User - 공지사항 목록 조회, 공지사항 상세 조회

[Feat] 공지사항 기능 구현

---

build.gradle
src/main/java/ddingdong/ddingdongBE/common/config/AmazonS3Config.java
src/main/java/ddingdong/ddingdongBE/domain/club/controller/CentralClubApiController.java
src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/DetailClubResponse.java
src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubService.java
src/main/java/ddingdong/ddingdongBE/domain/imageinformation/entity/ImageCategory.java
src/main/java/ddingdong/ddingdongBE/domain/imageinformation/entity/ImageInformation.java
src/main/java/ddingdong/ddingdongBE/domain/imageinformation/repository/ImageInformationRepository.java
src/main/java/ddingdong/ddingdongBE/domain/imageinformation/service/ImageInformationService.java
src/main/java/ddingdong/ddingdongBE/domain/notice/controller/AdminNoticeApiController.java
src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/response/DetailNoticeResponse.java
src/main/java/ddingdong/ddingdongBE/domain/notice/service/NoticeService.java
src/main/java/ddingdong/ddingdongBE/file/AwsS3FileStore.java
src/main/java/ddingdong/ddingdongBE/file/FileStore.java
src/main/java/ddingdong/ddingdongBE/file/dto/UploadFileDto.java
src/main/java/ddingdong/ddingdongBE/file/service/FileService.java
src/main/resources/application.yaml

- 이미지 정보 엔티티 구현
- 동아리 정보 수정 시 이미지 업로드/삭제 구현
- 공지사항 등록 시 이미지 업로드, 공지사항 수정시 이미지 업로드/삭제 구현
- 동아리, 공지사항 상세 조회 응답 이미지 url 추가

[Feat] 이미지 정보 기능 구현

---

src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/AdminActivityReportApiController.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/RegisterActivityReportRequest.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/UpdateActivityReportRequest.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/ActivityReportResponse.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/CurrentTermResponse.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/DetailActivityReportResponse.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/UpdateActivityReportResponse.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/domain/ActivityReport.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/domain/Participant.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/repository/ActivityReportRepository.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportService.java
src/main/java/ddingdong/ddingdongBE/domain/club/controller/CentralClubApiController.java
src/main/java/ddingdong/ddingdongBE/domain/club/entity/Club.java
src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubService.java
src/main/java/ddingdong/ddingdongBE/domain/imageinformation/entity/ImageCategory.java
src/main/java/ddingdong/ddingdongBE/domain/notice/service/NoticeService.java
src/main/java/ddingdong/ddingdongBE/domain/user/entity/User.java

[#11] 활동 보고서 API 작성

---

.platform/nginx/nginx.conf
src/main/java/ddingdong/ddingdongBE/auth/service/JwtAuthService.java
src/main/java/ddingdong/ddingdongBE/common/exception/ErrorMessage.java
src/main/java/ddingdong/ddingdongBE/common/filter/JwtAuthenticationFilter.java
src/main/java/ddingdong/ddingdongBE/common/handler/RestAuthenticationEntryPoint.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/ActivityReportDateRequest.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/RegisterActivityReportRequest.java
src/main/java/ddingdong/ddingdongBE/domain/banner/service/BannerService.java
src/main/java/ddingdong/ddingdongBE/domain/club/controller/CentralClubApiController.java
src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/request/RegisterClubRequest.java
src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/request/UpdateClubRequest.java
src/main/java/ddingdong/ddingdongBE/domain/club/entity/Club.java
src/main/java/ddingdong/ddingdongBE/domain/notice/controller/AdminNoticeApiController.java
src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/request/RegisterNoticeRequest.java
src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/request/UpdateNoticeRequest.java
src/main/resources/application-dev.yml
src/main/resources/application.yml
src/main/resources/data.sql

- 요청 바디 타입 변경
- 요청 파일 최대 크기 변경(최대 10M)
- jwt 토큰 예외 처리 추가
- 로컬 개발 환경 기본 데이터 추가
- club - user 테이블 remove cascade 추가

[fix]api 요청 수정사항 반영

---

src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/AdminClubResponse.java
src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubService.java

어드민 동아리 정보 조회 응답 이미저 url 정보 추가

[Ractor]어드민 동아리 정보 조회 수정

---

src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/RegisterActivityReportRequest.java

refactor : 활동보고서 등록 api 활동일자 날짜 형식 수정

refactor : 활동보고서 등록 api 활동일자 날짜 형식 수정

---

src/main/java/ddingdong/ddingdongBE/common/exception/ErrorMessage.java
src/main/java/ddingdong/ddingdongBE/domain/fileinformation/entity/FileDomainCategory.java
src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/AdminFixZoneController.java
src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/ClubFixZoneController.java
src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/request/CreateFixRequest.java
src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/request/UpdateFiXCompletionRequest.java
src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/request/UpdateFixRequest.java
src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/AdminDetailFixResponse.java
src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/AdminFixResponse.java
src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/ClubDetailFixResponse.java
src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/ClubFixResponse.java
src/main/java/ddingdong/ddingdongBE/domain/fixzone/entitiy/Fix.java
src/main/java/ddingdong/ddingdongBE/domain/fixzone/repository/FixRepository.java
src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FixZoneService.java

동아리
- 수리 신청서 생성
- 수리 신청서 수정
- 수리 신청서 삭제
- 수리 신청서 전체/상세 조회
어드민
- 수리 신청서 전체/상세 조회
- 수리 신청서 완료 여부 변경

[Feature]픽스존 api 구현

---

build.gradle
src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
src/main/java/ddingdong/ddingdongBE/domain/qrstamp/controller/QrStampController.java
src/main/java/ddingdong/ddingdongBE/domain/qrstamp/controller/dto/request/CollectStampRequest.java
src/main/java/ddingdong/ddingdongBE/domain/qrstamp/controller/dto/request/StudentInfoParam.java
src/main/java/ddingdong/ddingdongBE/domain/qrstamp/controller/dto/response/CollectedStampsResponse.java
src/main/java/ddingdong/ddingdongBE/domain/qrstamp/controller/dto/response/CollectionResultResponse.java
src/main/java/ddingdong/ddingdongBE/domain/qrstamp/entity/ClubStamp.java
src/main/java/ddingdong/ddingdongBE/domain/qrstamp/entity/StampHistory.java
src/main/java/ddingdong/ddingdongBE/domain/qrstamp/repository/StampHistoryRepository.java
src/main/java/ddingdong/ddingdongBE/domain/qrstamp/service/QrStampService.java

- 동아리 박람회 qr 기능 구현
- 동아리 도장 수집
- 동아리 도장 수집 내역 조회

feature: 동아리 박람회 qr 이벤트 기능 구현

---

.github/workflows/ddingdong-dev-deploy.yml
src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
src/main/java/ddingdong/ddingdongBE/common/utils/EventQrGenerator.java
src/main/java/ddingdong/ddingdongBE/domain/event/controller/EventController.java
src/main/java/ddingdong/ddingdongBE/domain/event/controller/dto/response/EventQrResponse.java
src/main/resources/application-local.yml

- close #46 
동아리 박람회 QR URI 생성

Feat/qr uri 생성 기능 구현

---

src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
src/main/java/ddingdong/ddingdongBE/domain/qrstamp/controller/AdminEventController.java
src/main/java/ddingdong/ddingdongBE/domain/qrstamp/controller/UserEventController.java
src/main/java/ddingdong/ddingdongBE/domain/qrstamp/controller/dto/response/AppliedUsersResponse.java
src/main/java/ddingdong/ddingdongBE/domain/qrstamp/controller/dto/response/DetailAppliedUserResponse.java
src/main/java/ddingdong/ddingdongBE/domain/qrstamp/repository/StampHistoryRepository.java
src/main/java/ddingdong/ddingdongBE/domain/qrstamp/service/QrStampService.java

- admin
- 응모 유저 전체 조회
- 응모 유저 상세 조회

feat: admin - 응모 내역 

---

src/main/java/ddingdong/ddingdongBE/domain/qrstamp/controller/dto/response/DetailAppliedUserResponse.java

refactor: admin - 응모 내역 상세 조회 수정

---

src/main/java/ddingdong/ddingdongBE/domain/club/controller/CentralClubApiController.java
src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/request/ClubMemberDto.java
src/main/java/ddingdong/ddingdongBE/domain/club/repository/ClubMemberRepository.java
src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubMemberService.java
src/main/java/ddingdong/ddingdongBE/domain/qrstamp/entity/ClubStamp.java

refactor: update club member list

---

src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportService.java
src/main/java/ddingdong/ddingdongBE/domain/user/entity/User.java
src/main/resources/application-local.yml
src/main/resources/application-test.yml
src/main/resources/data.sql

- [자료실 기능 구현 PR](https://github.com/COW-dev/ddingdong-be/pull/59)에서 놓친 오류 수정
- 메서드 명 변경으로 인한 컴파일 에러 수정
- test profile 환경 설정 변경
- h2db 동작 방식을 인메모리 방식으로 변경
- sql init(기초 데이터 삽입) X
- h2db의 USER 예약어 해결을 위해 기존에 사용하던 방식인 예약어 제거 코드가 제대로 동작하지 않아 user 테이블 명을 users로 변경하여 회피하는 방법을 사용했습니다.

PR[#59] build 오류 수정

---

.github/codeowners
src/main/resources/application-prod.yml
src/main/resources/application.yml

* 개발 서버를 별도로 생성하며 운영쪽 환경변수와 개발 환경변수를 분리하였습니다. 
* 현재는 `DEV_DB_USERNAME` 과 같이 prefix를 기준으로 분리하였지만 다소 복잡해져서 대안이 없을까 찾아봤는데요, github secret의 environment를 이용하면 같은 변수명을 이용하면서 환경별 분리가 가능하다네요...?? 
이것도 좀 더 자세히 알아본 뒤에 추후 반영해 보겠습니다!
* sentry는 별도로 사용하지 않는 것 같아 의존성을 제거하였습니다.
* s3는 우선 기존 운영서버랑 같이 물려 두었습니다. 개발서버에 s3 셋업도 필요할 것 같아요!
* codeowners 추가했습니다 :)

[DEV-000] 운영 환경 yml 파일 작성 및 개발 환경 yml 파일 수정

---

src/main/resources/application-dev.yml

* mysql dialect 설정을 변경하였습니다.
* 초기 스키마 설정을 위해 ddl-auto 정책을 create로 변경하였습니다.

[DEV-000] MySQL Dialect 및 ddl-auto 옵션 변경

---

.github/workflows/dev-server-deployer.yml
.github/workflows/dev-server-integrator.yml

* CD 스크립트를 수정하였습니다.
* 기존 실행중이던 이미지를 종료하기 위해 docker-compose down 명령어를 사용했으나 해당 명령어에서 volume까지 제거하는 side effect가 존재하여 개발 서버의 dummy data가 삭제되는 현상을 경험하였습니다.
* 따라서, 해당 구문을 제거하고 up 시에 --force-recreate 구문을 통해 컨테이너만 삭제시키도록 조치하였습니다.

[DEV-000] CD 배포 스크립트 수정

---

src/main/java/ddingdong/ddingdongBE/common/handler/RestAuthenticationEntryPoint.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java

활동보고서 수정 api 파일 첨부 오류 수정
- 활동보고서 수정 api의 mutlipartFile이`required = false`지만 null 체킹 코드가 누락되어 해당 로직 추가하여 수정하였습니다.
RestAuthenticationEntryPoint 클래스 수정
- exception Object에 대한 null 체킹 코드가 누락되어 불필요한 에러 로그가 계속 발생하여 해당 부분 로직 추가하였습니다.

[DEV-000] 활동보고서 수정 api 오류

---

.github/codeowners
src/main/java/ddingdong/ddingdongBE/DdingdongBeApplication.java

서버 타임존을 `Asia/Seoul`로 변경
(+)리뷰어 추가
- 서버 타임존은 UTC로 설정하고 Util클래스를 만들어 필요한 케이스에만 `Asia/Seoul`를 적용하는 방법도 고민했지만, 서버 시간을 UTC로 유지해야 하는 이유가 없기 때문에 서버 타임존 자체를 수정하는 방법을 사용했습니다.
혹시 다른 의견 있다면 말씀 부탁드립니다!

[DEV-34] 서버 타임존 변경

---

.github/workflows/dn-rule.yml

dn-rule workflow 스크립트 작성
- 매일 오전 10시 현재 열려있는 pr에 대해 update & alert 적용
- D-n 라벨 설정이 없을 시 D-3이 default로 적용되도록 설정
웹훅 메시지에 대한 추가 내용 필요하신거 있다면 의견 주시변 반영해두겠습니다!

[DEV-35] dn-rule 적용

---

src/main/resources/application-local.yml
src/main/resources/application-test.yml

오류가 나서 버전에 맞게 Dialect를 수정하였습니다.

[DEV-000]Dialect 오류 수정

---

src/main/resources/application-local.yml
src/main/resources/application-test.yml
src/test/java/ddingdong/ddingdongBE/domain/documents/service/DocumentServiceTest.java
src/test/java/ddingdong/ddingdongBE/domain/question/service/QuestionServiceTest.java

Service 테스트 시 오류 발생하는 것 수정하였습니다

[DEV-000] service 테스트 시 오류 수정

---

.github/workflows/dev-server-integrator.yml
Dockerfile
build.gradle
src/main/resources/application-test.yml
src/test/java/ddingdong/ddingdongBE/common/support/TestContainerSupport.java
src/test/resources/testcontainers.properties

TestContainer 도입 시 발생하는 Docker in Docker 문제 해결하였습니다.
아래는 트러블 슈팅 문서화한 것 입니다.
https://confusion-icebreaker-9cd.notion.site/TestContainer-CI-1da8ea2003a04c1fbd8d7078e5e11da1?pvs=4

[DEV-000] ci 도커 에러 수정

---

README.md

[DEV-000] README 적용

---

src/main/java/ddingdong/ddingdongBE/auth/service/JwtAuthService.java
src/main/java/ddingdong/ddingdongBE/common/exception/AuthenticationException.java
src/main/java/ddingdong/ddingdongBE/common/exception/CustomExceptionHandler.java
src/main/java/ddingdong/ddingdongBE/common/exception/ErrorMessage.java
src/main/java/ddingdong/ddingdongBE/common/exception/RegisterClubException.java

* CustomException handler method를 복구하였습니다.
* Auth exception handler의 응답 상태를 400 -> 401로 변경하였습니다.

[DEV-000] 에러 핸들러 명세 일부 수정

---

build.gradle
settings.gradle
src/main/java/ddingdong/ddingdongBE/common/BaseEntity.java
src/main/java/ddingdong/ddingdongBE/common/config/QueryDslConfig.java
src/main/java/ddingdong/ddingdongBE/common/exception/PersistenceException.java
src/main/java/ddingdong/ddingdongBE/domain/scorehistory/api/AdminScoreHistoryApi.java

* 추후 페이지네이션 적용을 위한 QueryDsl 셋업을 완료했습니다.

[DEV-41] querydsl 셋업

---

src/main/java/ddingdong/ddingdongBE/file/api/S3FileApi.java

uploadUrl 발급 API 응답 예시 설정 추가하였습니다.

[DEV-000] presignedUrl 발급 API 응답 예시 설정

---

src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/CreateActivityReportRequest.java

* 활동보고서 시작, 종료일자 null값은 직렬화 시 validation 제외 로직 추가

[DEV-000] 활동보고서 시작, 종료일자 null값은 직렬화 시 validation 제외 로직 추가

---

.github/workflows/dev-server-integrator.yml
src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/ClubActivityReportApi.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/CreateActivityReportRequest.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/UpdateActivityReportRequest.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/domain/ActivityReport.java
src/main/java/ddingdong/ddingdongBE/file/service/ExcelFileService.java
src/test/java/ddingdong/ddingdongBE/file/service/ExcelFileServiceTest.java

* @ModelAttribute를 사용하던 Request DTO에서 @RequestPart로 롤백

[DEV-000] @ModelAttribute를 사용하던 Request DTO에서 @RequestPart로 롤백

---

src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportService.java

* 활동보고서 현재 회차 term을 1 -> 8로 변경했습니다.

[DEV-000] 활동보고서 현재 회차 정보 변경

---

.github/workflows/dev-server-integrator.yml
src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportService.java
src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/request/GenerateDocumentRequest.java
src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/request/ModifyDocumentRequest.java
src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/AdminDetailDocumentResponse.java
src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/DetailDocumentResponse.java
src/main/java/ddingdong/ddingdongBE/domain/documents/entity/Document.java
src/main/resources/db/migration/V3__document_delete_content_column.sql
src/test/java/ddingdong/ddingdongBE/domain/documents/controller/AdminDocumentControllerUnitTest.java
src/test/java/ddingdong/ddingdongBE/domain/documents/controller/DocumentControllerUnitTest.java
src/test/java/ddingdong/ddingdongBE/domain/documents/service/DocumentServiceTest.java

* 활동보고서 현재 회차 정보 변경
- 자료실 불필요 필드(content) 제거

[DEV-000] 활동보고서 현재 회차 정보 변경 및 자료실 불필요 필드 제거

---

src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/AdminActivityReportApi.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/ClubActivityReportApi.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/AdminActivityReportApiController.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/CreateActivityReportRequest.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/domain/ActivityReport.java

[release] v1.0.1

---

src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/request/RegisterClubRequest.java
src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/AdminClubResponse.java
src/main/java/ddingdong/ddingdongBE/domain/club/entity/Club.java
src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubService.java
src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/dto/request/CreateScoreHistoryRequest.java
src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/dto/response/ScoreHistoryFilterByClubResponse.java
src/main/java/ddingdong/ddingdongBE/domain/scorehistory/entity/Score.java
src/main/java/ddingdong/ddingdongBE/domain/scorehistory/entity/ScoreHistory.java
src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/ScoreHistoryService.java
src/test/java/ddingdong/ddingdongBE/domain/scorehistory/controller/AdminScoreHistoryControllerUnitTest.java
src/test/java/ddingdong/ddingdongBE/domain/scorehistory/controller/ClubScoreHistoryControllerUnitTest.java

동아리 점수 타입을 float -> BigDecimal로 변경하였습니다.
소수점 셋째자리에서 반올림을 하였는데, 그냥 반올림 대신 넷째자리를 버리는 것으로 할까요??

[DEV-000] 동아리 점수 타입 변경

---

src/main/resources/application-local.yml
src/main/resources/data.sql
src/main/resources/db/migration/V4__Create_feed.sql
src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeClubMemberServiceTest.java
src/test/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepositoryTest.java
src/test/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedServiceTest.java

- fixtureMonkey를 통해 club entity 생성 시, Score(BigDecimal)타입 제약조건 만족하는 범위로 설정
++ 추가로 local 환경 데이터 세팅 오류 수정했습니다!

[DEV-000] CI(test) 오류 수정

---

src/main/java/ddingdong/ddingdongBE/domain/feed/entity/Feed.java
src/main/resources/db/migration/V4__Create_feed.sql

- Feed 엔티티 activity_content 컬럼 타입 수정
- text -> varchar(100)

[DEV-000] Feed 엔티티 컬럼 타입 수정

---

src/test/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepositoryTest.java
src/test/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedServiceTest.java

테스트 중 Score 점수 입력을 확인하지 못했던 것이 발견되어 수정하였습니다.

[DEV-000] feedRepositoryTest 에러 수정

---

src/main/java/ddingdong/ddingdongBE/domain/feed/controller/dto/response/FeedResponse.java
src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedService.java
src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/ClubInfo.java
src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/ClubInformationQuery.java
src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/ClubProfileQuery.java
src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/FeedQuery.java
src/test/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepositoryTest.java
src/test/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedServiceTest.java

프론트 분들의 요청에 따라 피드 상세조회API 응답값에 동아리 ID를 추가하였습니다

[DEV-000] 동아리 피드 상세조회 API 응답값에 동아리 ID 추가 

---

src/main/resources/db/migration/V8__apply_key_name_convention.sql

V7에서 제거된 stamp_history테이블 관련 SQL문 제거하였습니다.

[DEV-000] Flyway V8 스크립트 에러 수정

---

src/main/java/ddingdong/ddingdongBE/domain/feed/api/FeedApi.java
src/main/java/ddingdong/ddingdongBE/domain/feed/entity/Feed.java
src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedService.java
src/main/resources/application-local.yml
src/test/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedServiceTest.java

[DEV-000] Hotfix - 프로필 이미지 에러 수정

---

build.gradle
src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
src/main/java/ddingdong/ddingdongBE/domain/club/entity/PhoneNumber.java
src/main/resources/application-prod.yml
src/main/resources/application.yml

`v1.1.0` -> `v1.1.1` 버전 배포 내역입니다.
* 동아리 연락처 형식 검증을 위한 정규 표현식 변경
* prometheus, grafana 의존성 추가

[release] v1.1.1

---

src/main/java/ddingdong/ddingdongBE/domain/club/entity/PhoneNumber.java
src/main/resources/application-prod.yml

[DEV-000] VO에 @EqualsAndHashCode 적용

---

src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/ActivityReportResponse.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/ActivityReportQuery.java

대문자로 되어있던 것 소문자로 수정했습니다.
ImageUrls -> imageUrls

[DEV-000] ActivityReport 응답 필드명 수정

---

src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportService.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportService.java

활동보고서 삭제시 발생하는 오류 해결하였습니다.
기존 활동보고서 조회 시 빈 배열을 반환하는 경우도 필요하기에, 예외 처리를 동반한 조회 메소드 추가하였습니다

[DEV-000] 활동보고서 삭제 API 에러 수정

---

src/main/java/ddingdong/ddingdongBE/domain/documents/controller/AdminDocumentController.java
src/main/java/ddingdong/ddingdongBE/domain/documents/controller/DocumentController.java
src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/request/CreateDocumentRequest.java
src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/request/UpdateDocumentRequest.java
src/main/java/ddingdong/ddingdongBE/domain/documents/service/FacadeAdminDocumentService.java
src/main/java/ddingdong/ddingdongBE/domain/documents/service/dto/command/CreateDocumentCommand.java
src/main/java/ddingdong/ddingdongBE/domain/documents/service/dto/command/UpdateDocumentCommand.java
src/test/java/ddingdong/ddingdongBE/domain/documents/controller/AdminDocumentControllerUnitTest.java

controller 모든 데이터 Command DTO를 사용하여 이동하도록 수정하였습니다

[DEV-000] Document도메인 Controller -> Service 데이터 이동 방법 수정

---

src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/response/NoticeResponse.java
src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeNoticeService.java
src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/query/NoticeQuery.java

[DDING-000] CI 실패 부분 수정

---

src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/AdminClubListResponse.java

- AdminClubListResponse null 체킹 추가

[DDING-000] api 오류 수정

---

src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/DocumentResponse.java
src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeAdminNoticeServiceImpl.java

[DDING-000] 깃 버전 충돌 및 컴파일 오류 해결

---

src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImpl.java
src/main/resources/db/migration/V23__alter_table_document_drop_column.sql
src/main/resources/db/migration/V26__alter_table_activityreport_drop_column.sql

- FileMetaDataService null 체킹 로직 추가
- migration script 불필요 스키마 명 제거

[DDING-000] FileMetaDataService null 체킹 로직 추가

---

src/main/java/ddingdong/ddingdongBE/common/utils/TimeParser.java

StartTime, EndTime에 null값 주입시 null값 반환하도록 수정하였습니다

[DDING-000] ActivityReport 시작일자 및 종료일자 관련 에러 수정

---

compose-dev.yaml

compose 파일에 mysql 이미지 내 볼륨 설정 추가하였습니다

[DDING-000] mysql 컨테이너 볼륨 설정

---

compose-dev.yaml

* 개발 환경 DB 테이블 복구를 위한 볼륨 연결 스크립트를 추가하였습니다.

[DDING-000] 테이블 복구를 위한 볼륨 연결 스크립트 추가

---

compose-dev.yaml

* mysql 버전 8.0.33 -> 8.0.40으로 마이그레이션 시도

[DDING-000] mysql 버전 8.0.33 -> 8.0.40으로 마이그레이션

---

.github/workflows/dev-server-integrator.yml
compose-dev.yaml

[DDING-000] compose-dev.yml 스크립트 롤백

---

src/main/java/ddingdong/ddingdongBE/domain/documents/repository/DocumentRepository.java
src/main/java/ddingdong/ddingdongBE/domain/notice/repository/NoticeRepository.java

soft delete된 엔터티 조회하지 않도록 조건 수정했습니다

[DDING-000] 페이지네이션 조회 시 조건 수정

---

.github/workflows/dev-server-integrator.yml
compose-dev.yaml

[DDING-000] mysql 도커 볼륨 명시적 설정

---

src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImpl.java

일부 id를 제거하고, id를 새로 추가할 때 발생하는 에러 수정하였습니다

[DDING-000] FileMetaData update시 일부 id 변경 시 에러 수정

---

src/main/java/ddingdong/ddingdongBE/file/service/S3FileService.java

[DDING-000] videoUrl directory path 수정

---

src/main/java/ddingdong/ddingdongBE/file/service/S3FileService.java

[DDING-000] videoUrl directory path 수정(2)

---

src/main/java/ddingdong/ddingdongBE/domain/feed/controller/dto/response/MyFeedPageResponse.java
src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeClubFeedServiceImpl.java
src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedService.java
src/main/java/ddingdong/ddingdongBE/domain/feed/service/GeneralFeedService.java
src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/ClubFeedPageQuery.java
src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/MyFeedPageQuery.java
src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/NewestFeedPerClubPageQuery.java
src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/PagingQuery.java

[DDING-000] 피드가 존재하지 않을 경우 발생하는 에러 수정

---

.github/codeowners

[DDING-000] CodeOwner 수정

---

.github/codeowners
src/main/java/ddingdong/ddingdongBE/domain/club/repository/ClubRepository.java
src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubService.java
src/main/java/ddingdong/ddingdongBE/domain/club/service/GeneralClubService.java
src/main/java/ddingdong/ddingdongBE/domain/clubmember/service/FacadeCentralClubMemberServiceImpl.java
src/main/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepository.java
src/main/java/ddingdong/ddingdongBE/domain/feed/service/GeneralFeedService.java
src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/dto/response/AdminScoreHistoryListResponse.java
src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/dto/response/ClubScoreHistoryListResponse.java
src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/FacadeAdminScoreHistoryServiceImpl.java
src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/FacadeClubScoreHistoryServiceImpl.java
src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/dto/query/AdminClubScoreHistoryListQuery.java
src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/dto/query/ClubScoreHistoryListQuery.java
src/main/java/ddingdong/ddingdongBE/file/controller/S3FileController.java
src/test/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepositoryTest.java

- OSIV 설정으로 인한 에러 수정
- 파일명 decoding 로직 추가
- 피드 조회 검증 로직 [애플리케이션 레벨 -> 쿼리] 로 변경

[release] v.1.2.1

---

src/test/java/ddingdong/ddingdongBE/domain/form/repository/FormApplicationRepositoryTest.java
src/test/java/ddingdong/ddingdongBE/domain/form/repository/FormFieldRepositoryTest.java
src/test/java/ddingdong/ddingdongBE/domain/form/repository/FormRepositoryTest.java
src/test/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormApplicationServiceImplTest.java
src/test/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImplTest.java
src/test/java/ddingdong/ddingdongBE/domain/form/service/FacadeUserFormApplicationServiceImplTest.java
src/test/java/ddingdong/ddingdongBE/domain/form/service/FacadeUserFormServiceImplTest.java
src/test/java/ddingdong/ddingdongBE/domain/form/service/FormStatisticServiceImplTest.java

- monkey builder 사용으로 인해 랜덤 값 주입으로 계속 테스트 실패하여 주석처리했습니다

[DDING-000] 테스트 실패로 인한 주석처리

---

src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeUserClubServiceImpl.java

- 동아리 조회 시 동아리 모집 기간 체크 로직 수정
- 조회 날짜와 모집 마감 날짜가 같을 시 모집 마감으로 처리 -> 모집중으로 처리

[DDING-000] 동아리 모집 기간 체크 로직 수정

---

src/main/java/ddingdong/ddingdongBE/domain/club/entity/Club.java
src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeUserClubServiceImpl.java
src/main/java/ddingdong/ddingdongBE/domain/form/api/CentralFormApi.java
src/main/java/ddingdong/ddingdongBE/domain/form/controller/CentralFormController.java
src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/request/SendApplicationResultEmailRequest.java
src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/command/SendApplicationResultEmailCommand.java
src/main/java/ddingdong/ddingdongBE/email/dto/EmailContent.java

- 동아리 지원 결과 메일 전송 템플릿 수정
- 발신전용 메시지 문구 추가

[DDING-000] 동아리 지원 결과 메일 전송 템플릿 수정

---

src/main/resources/application-prod.yml

- OSIV 속성 false로 인해 활동보고서 도메인 로직에서 문제 발생
- 활동보고서 응답 객체dto 생성 시 프록시 객체를 통해 생성하기 때문에 service레이어를 벗어나는 순간 프록시 객체 접근이 불가능하여 문제 발생
- `open-in-view: true` 로 변경

[DDING-000] OSIV 속성 on

---

src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportTermInfoService.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportTermInfoServiceImpl.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportService.java
src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportServiceImpl.java
src/main/resources/db/migration/V42__alter_table_add_index_activity_report.sql

[release] v1.3.2

---

src/main/resources/db/migration/V41__alter_table_form_field_option.sql

[release] v.1.3.7

---

.ebextensions/00-makeFiles.config

[DDING-000] 힙 메모리 최대치 수정

---

.ebextensions/00-makeFiles.config

[release] v1.3.9

---

.ebextensions/00-makeFiles.config
.ebextensions/03-swap-file.config
.ebextensions/04-create-env-file.config
Dockerfile
alloy/config.alloy
src/main/java/ddingdong/ddingdongBE/common/runner/AlloyDockerComposeRunner.java
src/main/java/ddingdong/ddingdongBE/common/runner/PromtailDockerComposeRunner.java

[release] v1.4.1
